"""Business logic — one module per skill (setup, scrape, rank, apply, ...)."""

from app.services import (
    add_portal,
    add_template,
    apply,
    ats_check,
    auth,
    cv_cutter,
    expand,
    interview,
    outcome,
    pdf_compiler,
    pipeline_reset,
    provider_credentials,
    provider_models,
    rank,
    reset,
    scrape,
    setup,
    upskill,
)

__all__ = [
    "add_portal",
    "add_template",
    "apply",
    "ats_check",
    "auth",
    "cv_cutter",
    "expand",
    "interview",
    "outcome",
    "pdf_compiler",
    "pipeline_reset",
    "provider_credentials",
    "provider_models",
    "rank",
    "reset",
    "scrape",
    "setup",
    "upskill",
]