"""add_pipeline_stage_and_review_to_applications

Revision ID: 113c1bad5c0a
Revises: d5e6f7a8b9c0
Create Date: 2026-07-14 20:44:17.706840

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "113c1bad5c0a"
down_revision: str | None = "d5e6f7a8b9c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column(
            "pipeline_stage",
            sa.String(length=20),
            nullable=False,
            comment="draft → reviewed → revised → compiled → verified",
        ),
    )
    op.add_column(
        "applications",
        sa.Column(
            "review_feedback",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.add_column(
        "applications",
        sa.Column(
            "review_issues",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_execution_jobs_status_pipeline"), table_name="execution_jobs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_execution_jobs_status_pipeline"), "execution_jobs", ["status", "pipeline"], unique=False)
    op.drop_column("applications", "review_issues")
    op.drop_column("applications", "review_feedback")
    op.drop_column("applications", "pipeline_stage")
    # ### end Alembic commands ###
