"""add job_target to candidate_profiles

Revision ID: 5e788b9bfd16
Revises: d4e5f6a7b8c9
Create Date: 2026-07-21 17:14:45.240055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e788b9bfd16'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_job_posting_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.add_column('candidate_profiles', sa.Column('job_target', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.drop_index(op.f('ix_competency_expansions_candidate_id'), table_name='competency_expansions')
    op.drop_index(op.f('ix_competency_expansions_user_id'), table_name='competency_expansions')
    op.drop_index(op.f('ix_execution_jobs_user_id'), table_name='execution_jobs')
    op.drop_index(op.f('ix_interview_preps_application_id'), table_name='interview_preps')
    op.drop_index(op.f('ix_interview_preps_user_id'), table_name='interview_preps')
    op.drop_index(op.f('ix_job_postings_user_id'), table_name='job_postings')
    op.drop_index(op.f('ix_outcomes_application_id'), table_name='outcomes')
    op.drop_index(op.f('ix_outcomes_user_id'), table_name='outcomes')
    op.drop_index(op.f('ix_provider_credentials_user_id'), table_name='provider_credentials')
    op.drop_index(op.f('ix_rank_evaluations_user_id'), table_name='rank_evaluations')
    op.drop_index(op.f('ix_scrape_runs_user_id'), table_name='scrape_runs')
    op.drop_index(op.f('ix_star_examples_candidate_id'), table_name='star_examples')
    op.drop_index(op.f('ix_upskills_candidate_id'), table_name='upskills')
    op.drop_index(op.f('ix_upskills_user_id'), table_name='upskills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_upskills_user_id'), 'upskills', ['user_id'], unique=False)
    op.create_index(op.f('ix_upskills_candidate_id'), 'upskills', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_star_examples_candidate_id'), 'star_examples', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_scrape_runs_user_id'), 'scrape_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_rank_evaluations_user_id'), 'rank_evaluations', ['user_id'], unique=False)
    op.create_index(op.f('ix_provider_credentials_user_id'), 'provider_credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_outcomes_user_id'), 'outcomes', ['user_id'], unique=False)
    op.create_index(op.f('ix_outcomes_application_id'), 'outcomes', ['application_id'], unique=False)
    op.create_index(op.f('ix_job_postings_user_id'), 'job_postings', ['user_id'], unique=False)
    op.create_index(op.f('ix_interview_preps_user_id'), 'interview_preps', ['user_id'], unique=False)
    op.create_index(op.f('ix_interview_preps_application_id'), 'interview_preps', ['application_id'], unique=False)
    op.create_index(op.f('ix_execution_jobs_user_id'), 'execution_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_competency_expansions_user_id'), 'competency_expansions', ['user_id'], unique=False)
    op.create_index(op.f('ix_competency_expansions_candidate_id'), 'competency_expansions', ['candidate_id'], unique=False)
    op.drop_column('candidate_profiles', 'job_target')
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_index(op.f('ix_applications_job_posting_id'), 'applications', ['job_posting_id'], unique=False)
    # ### end Alembic commands ###