"""add_external_sources_to_scrape_runs

Revision ID: 79905e25e8c5
Revises: e1f2a3b4c5d6
Create Date: 2026-07-22 00:39:08.450934

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79905e25e8c5"
down_revision: str | None = "e1f2a3b4c5d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scrape_runs",
        sa.Column(
            "external_sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.add_column(
        "scrape_runs",
        sa.Column(
            "external_results",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scrape_runs", "external_results")
    op.drop_column("scrape_runs", "external_sources")
    # ### end Alembic commands ###
