"""add_draft_tex_fields_to_applications

Revision ID: ab1ceebdb9d5
Revises: 113c1bad5c0a
Create Date: 2026-07-14 21:17:04.395921

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab1ceebdb9d5"
down_revision: str | None = "113c1bad5c0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column("draft_cv_tex", sa.Text(), nullable=True, comment="First draft CV LaTeX before review"),
    )
    op.add_column(
        "applications",
        sa.Column(
            "draft_cover_letter_tex", sa.Text(), nullable=True, comment="First draft cover letter LaTeX before review"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "draft_cover_letter_tex")
    op.drop_column("applications", "draft_cv_tex")
    # ### end Alembic commands ###
