"""add_draft_tex_fields_to_applications

Revision ID: ab1ceebdb9d5
Revises: 113c1bad5c0a
Create Date: 2026-07-14 21:17:04.395921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1ceebdb9d5'
down_revision: Union[str, None] = '113c1bad5c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('draft_cv_tex', sa.Text(), nullable=True, comment='First draft CV LaTeX before review'))
    op.add_column('applications', sa.Column('draft_cover_letter_tex', sa.Text(), nullable=True, comment='First draft cover letter LaTeX before review'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'draft_cover_letter_tex')
    op.drop_column('applications', 'draft_cv_tex')
    # ### end Alembic commands ###