"""add_ats_check_fields_to_applications

Revision ID: ece27c8ea724
Revises: ab1ceebdb9d5
Create Date: 2026-07-14 21:20:18.567363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ece27c8ea724'
down_revision: Union[str, None] = 'ab1ceebdb9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('ats_score', sa.Float(), nullable=True, comment='ATS keyword coverage 0.0-1.0 (None = check not run)'))
    op.add_column('applications', sa.Column('ats_missing_keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='Job keywords not found in PDF text'))
    op.add_column('applications', sa.Column('ats_pass', sa.Boolean(), nullable=True, comment='Overall ATS compatibility verdict'))
    op.add_column('applications', sa.Column('ats_checked_at', sa.DateTime(timezone=True), nullable=True, comment='When ATS check was performed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'ats_checked_at')
    op.drop_column('applications', 'ats_pass')
    op.drop_column('applications', 'ats_missing_keywords')
    op.drop_column('applications', 'ats_score')
    # ### end Alembic commands ###